CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  google_sub text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  display_name varchar(80) NOT NULL,
  avatar_url text,
  bio varchar(300),
  role varchar(20) NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'moderator', 'admin')),
  status varchar(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(50) NOT NULL UNIQUE,
  name varchar(50) NOT NULL,
  description varchar(160) NOT NULL,
  icon varchar(8) NOT NULL,
  color varchar(16) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS threads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id integer NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title varchar(120) NOT NULL,
  body text NOT NULL CHECK (char_length(body) BETWEEN 20 AND 20000),
  tags text[] NOT NULL DEFAULT '{}',
  status varchar(20) NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'hidden', 'locked', 'deleted')),
  is_pinned boolean NOT NULL DEFAULT false,
  reply_count integer NOT NULL DEFAULT 0 CHECK (reply_count >= 0),
  view_count bigint NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  like_count integer NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  search_document tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(body, ''))
  ) STORED
);

CREATE TABLE IF NOT EXISTS posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  body text NOT NULL CHECK (char_length(body) BETWEEN 2 AND 10000),
  status varchar(20) NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'hidden', 'deleted')),
  is_solution boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS thread_likes (
  thread_id uuid NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (thread_id, user_id)
);

CREATE TABLE IF NOT EXISTS bookmarks (
  thread_id uuid NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (thread_id, user_id)
);

CREATE TABLE IF NOT EXISTS reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  thread_id uuid REFERENCES threads(id) ON DELETE CASCADE,
  post_id uuid REFERENCES posts(id) ON DELETE CASCADE,
  reason varchar(40) NOT NULL,
  detail varchar(1000),
  status varchar(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((thread_id IS NOT NULL)::integer + (post_id IS NOT NULL)::integer = 1)
);

CREATE TABLE IF NOT EXISTS user_sessions (
  sid varchar NOT NULL PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_threads_feed ON threads (is_pinned DESC, last_activity_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_threads_category_feed ON threads (category_id, last_activity_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_threads_author ON threads (author_id, created_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_threads_popular ON threads (like_count DESC, last_activity_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_threads_search ON threads USING gin (search_document);
CREATE INDEX IF NOT EXISTS idx_threads_title_trgm ON threads USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_threads_body_trgm ON threads USING gin (body gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_threads_tags ON threads USING gin (tags);
CREATE INDEX IF NOT EXISTS idx_posts_thread ON posts (thread_id, created_at, id) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON bookmarks (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_open ON reports (created_at) WHERE status IN ('open', 'reviewing');
CREATE INDEX IF NOT EXISTS idx_user_sessions_expire ON user_sessions (expire);

INSERT INTO categories (id, slug, name, description, icon, color, sort_order) VALUES
  (1, 'lounge', 'ラウンジ', '日常のこと、ふと思ったこと', '☕', '#ff6b4a', 10),
  (2, 'technology', 'テクノロジー', '開発・AI・ガジェットの話', '⌘', '#6c5ce7', 20),
  (3, 'creative', 'クリエイティブ', '写真、音楽、文章、ものづくり', '✦', '#e84393', 30),
  (4, 'questions', '質問・相談', 'みんなの知恵を借りよう', '?', '#0984e3', 40),
  (5, 'local', 'ローカル', '街・イベント・おでかけ情報', '⌖', '#00a884', 50)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  sort_order = EXCLUDED.sort_order;

SELECT setval(pg_get_serial_sequence('categories', 'id'), GREATEST((SELECT max(id) FROM categories), 1));
